### ISSUE TITLE
Doc: Provide a more involved config file (example provided)

### ISSUE THREAD

**Issue by jakubholynet** [crccheck/cloudwatch-to-graphite#21]
The provided sample config file is little to simple to be useful, especially for those not too familiar with YAML. Here is a more complex one that avoids duplication via YAML anchor+alias. It would be helpful to include some of this, I believe.

```yaml
# Define defaults that can be referenced below
My_Defaults:
  - &ElbMetric
    Namespace: "AWS/ELB"
    Dimensions:
      # You can have multiple dimensions, but boto will only return the last one
      LoadBalancerName: "awseb-e-v-AWSEBLoa-ZELK76TU0GP"
Auth:
  region: "us-west-1"
Metrics:
- <<: *ElbMetric
  MetricName: "RequestCount"
  Statistics: "Sum"
  Unit: "Count"
# You can list additional metrics in one file. Just be careful about rate limits.
- <<: *ElbMetric
  MetricName: "UnHealthyHostCount"
  Statistics: "Maximum"
  Unit: "Count"
# You can list additional metrics in one file. Just be careful about rate limits.
- <<: *ElbMetric
  MetricName: "Latency"
  Statistics:
  - "Average"
  - "Maximum"
  Unit: "Seconds"
- <<: *ElbMetric
  MetricName: "HTTPCode_ELB_5XX"
  Statistics: "Sum"
  Unit: "Count"
# OPTIONAL: set defaults for all metrics in this file
Options:
  Count: 1 # How many Periods to return (note: there is a max num datapoints you can get at once)
  Period: 5 # [min], minimum 1
```

Thank you!
